providers:
  priority:
    - models.dev
    - openrouter
boosts:
  - Claude-Sonnet-4.5
  - Gemini-2.5-Pro
  - GPT-5
exclusions:
  - assistant
  - id: web-search
    reason: not relevant
  - owner: poe
    reason: we are not model providers
  - owner: opentools
    reason: just tools, not models
  - Claude-Opus-4-Search
  - Claude-Sonnet-4-Search
  - Claude-Sonnet-3.7-Search
  - Claude-Haiku-3.5-Search
