providers:
  priority:
    - models.dev
    - openrouter
exclusions:
  - assistant
  - id: web-search
    reason: not relevant
  - owner: poe
    reason: we are not model providers
  - owner: opentools
    reason: just tools, not models
overrides:
  ChatGPT-4o-Latest:
    metadata:
      curated: true
      tier: flagship
    tags:
      - openai
      - flagship
