model_mapping:
  ChatGPT-4o-Latest:
    models.dev: openai/gpt-4o-2024-11-20
  Claude-Haiku-3:
    models.dev: anthropic/claude-3-haiku-20240307
  Claude-Haiku-3.5:
    models.dev: anthropic/claude-3-5-haiku-latest
  Claude-Haiku-3.5-Search:
    models.dev: anthropic/claude-3-5-haiku-latest
  Claude-Haiku-4.5:
    models.dev: anthropic/claude-haiku-4-5
  Claude-Opus-3:
    models.dev: anthropic/claude-3-opus-20240229
  Claude-Opus-4-Reasoning:
    models.dev: anthropic/claude-opus-4-20250514
  Claude-Opus-4-Search:
    models.dev: anthropic/claude-opus-4-0
  Claude-Opus-4.1:
    models.dev: anthropic/claude-opus-4-1
  Claude-Sonnet-3.5:
    models.dev: anthropic/claude-3-5-sonnet-20241022
  Claude-Sonnet-3.5-June:
    models.dev: anthropic/claude-3-5-sonnet-20240620
  Claude-Sonnet-3.7:
    models.dev: anthropic/claude-3-7-sonnet-latest
  Claude-Sonnet-3.7-Reasoning:
    models.dev: anthropic/claude-3-7-sonnet-latest
  Claude-Sonnet-3.7-Search:
    models.dev: anthropic/claude-3-7-sonnet-latest
  Claude-Sonnet-4-Reasoning:
    models.dev: anthropic/claude-sonnet-4-0
  Claude-Sonnet-4-Search:
    models.dev: anthropic/claude-sonnet-4-0
  GPT-4o-Aug:
    models.dev: openai/gpt-4o-2024-08-06
  GPT-5-Chat:
    models.dev: openai/gpt-5
  GPT-OSS-120B:
    models.dev: openai/text-embedding-3-large
  GPT-OSS-20B:
    models.dev: openai/text-embedding-3-small
  Gemini-2.0-Flash-Preview:
    models.dev: google/gemini-2.5-flash-preview-05-20
  Gemini-2.5-Flash-TTS:
    models.dev: google/gemini-2.5-flash-preview-tts
  Gemini-2.5-Pro-TTS:
    models.dev: google/gemini-2.5-pro-preview-tts
  Mistral-Large-2:
    models.dev: mistral/mistral-large-latest
  Mistral-Medium:
    models.dev: mistral/mistral-medium-2505
  Mistral-Medium-3:
    models.dev: mistral/mistral-medium-2505
  Mistral-Medium-3.1:
    models.dev: mistral/mistral-medium-2508
  Nano-Banana:
    models.dev: google/gemini-2.5-flash-image
  Mistral-Small-3:
    models.dev: mistral/mistral-small-latest
  Grok-4-Fast-Reasoning:
    models.dev: xai/grok-4-fast
